version: '3.2'

services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:25.0
    command: "-fallbackfee=0.0002"
    volumes:
      - bitcoin:/srv/app/.bitcoin

  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.9.14
    volumes:
      - electrs:/srv/app/db
    ports:
      - 50001:50001
    depends_on:
      - bitcoind

  proxy:
      image: ghcr.io/rgb-tools/rgb-proxy-server:0.2.1
      ports:
        - 3030:3000

volumes:
  bitcoin:
  electrs:
